doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            point:  App\Infrastructure\Database\DBAL\PointType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_mapping: true\
        proxy_namespace: Proxies
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        default_entity_manager: default
        mappings:
            AppDomainSegment:
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Segment'
                is_bundle: false
                prefix: App\Domain\Segment
            AppInfrastructureTask:
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Task'
                is_bundle: false
                prefix: App\Infrastructure\Task